/* Autogenerated code */

export interface Config {
  apps: {
    api: {
      port: number;
      privatePort: number;
      useCachingInterceptor: boolean;
    };
    cacheWarmer: {
      port: number;
    };
    queueWorker: {
      port: number;
    };
  };
  libs: {
    common: {
      pinata: {
        pinataUrl: string;
        pinataJwt: string;
        fileStorageCdnUrl: string;
      };
      network: "devnet" | "testnet" | "mainnet";
      urls: {
        api: string;
        gateway: string;
      };
      database: {
        host: string;
        port: number;
        username?: string;
        password?: string;
        name: string;
        tlsAllowInvalidCertificates: boolean;
      };
      redis: {
        host: string;
        port: number;
      };
      security: {
        admins: string[];
      };
      rateLimiterSecret?: string;
    };
  };
}
